# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Image
  jobs: 
  - job: Build
    displayName: Build
    pool:
     vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Marius Docker Hub'
        repository: 'mariusdorin83/simpleapi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)

- stage: Provision
  displayName: 'Terraforiming on Azure..'
  dependsOn: Build
  jobs:
  - job: Provision
    displayName: 'Provisioning Container Instance'
    pool:
     vmImage: 'ubuntu-latest'
    variables:
    - group: TerraformEnvVars
    steps: 
    - script: |
         set -e

         terraform init -input=false
         terraform apply -input=false -auto=approve
      name: 'RunTerraform'
      displayName: 'Run Terraform'
      env: 
         ARM_CLIENT_ID: $(ARM_CLIENT_ID)
         ARM_TENANT_ID: $(ARM_CLIENT_SECRET)
         ARM_CLIENT_SECRET: $(ARM_TENANT_ID)
         ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
